#Importing library

# Importing Library


In [1]:
import numpy as np

# Successfully installed!

# Array Attributes 

In [8]:
a=np.array([1,2,3]) #1-D/vector

In [3]:
a

array([1, 2, 3])

In [4]:
type(a)

numpy.ndarray

In [5]:
a.shape

(3,)

In [9]:
a.ndim

1

In [7]:
a.ndim

1

In [10]:
b=np.array([[1,2,3],
            [3,4,5]])

In [11]:
b

array([[1, 2, 3],
       [3, 4, 5]])

In [12]:
type(b)

numpy.ndarray

In [13]:
b.shape

(2, 3)

In [20]:
c=np.array([[[1.0,2,3],
             [2,3,4],
             [3,4,5]]])
d=np.array([[[1,2,3],
             [2,3,4],
             [4,4,5]],
            [[1,2,3],
             [2,3,4],
             [5,6,7]]])

In [21]:
c

array([[[1., 2., 3.],
        [2., 3., 4.],
        [3., 4., 5.]]])

In [16]:
d

array([[[1, 2, 3],
        [2, 3, 4],
        [4, 4, 5]],

       [[1, 2, 3],
        [2, 3, 4],
        [5, 6, 7]]])

In [17]:
d.shape

(2, 3, 3)

In [18]:
c.shape

(1, 3, 3)

In [22]:
a.dtype,b.dtype,c.dtype,d.dtype

(dtype('int64'), dtype('int64'), dtype('float64'), dtype('int64'))

In [23]:
a.size,b.size,c.size,d.size # detrmine the number of element 

(3, 6, 9, 18)

In [25]:
a.nbytes,b.nbytes,c.nbytes,d.nbytes # how  many bytes consume by each array

(24, 48, 72, 144)