# Array creation

In [2]:
import numpy as np

In [3]:
a=np.array([1,2,3])

In [4]:
a

array([1, 2, 3])

In [5]:
z=np.zeros((2,2),dtype='int')

In [6]:
z

array([[0, 0],
       [0, 0]])

In [7]:
one=np.ones((3,3),dtype='int')

In [8]:
one

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [9]:
full=np.full((2,3),5)

In [10]:
full

array([[5, 5, 5],
       [5, 5, 5]])

In [13]:
identity=np.identity(3,dtype='int')

In [14]:
identity

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [15]:
eye=np.eye(3,3,1)

In [16]:
eye

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [17]:
arange=np.arange(1,10,2)

In [18]:
arange

array([1, 3, 5, 7, 9])

In [19]:
linspace=np.linspace(1,10,10,dtype='int')

In [20]:
linspace

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [21]:
linsp=np.linspace(1,100,50,dtype='int')

In [22]:
linsp

array([  1,   3,   5,   7,   9,  11,  13,  15,  17,  19,  21,  23,  25,
        27,  29,  31,  33,  35,  37,  39,  41,  43,  45,  47,  49,  51,
        53,  55,  57,  59,  61,  63,  65,  67,  69,  71,  73,  75,  77,
        79,  81,  83,  85,  87,  89,  91,  93,  95,  97, 100])

In [23]:
empty=np.empty((1,5))

In [24]:
empty

array([[0.00000000e+000, 8.99402120e-312, 8.99402121e-312,
        8.99402120e-312, 0.00000000e+000]])

In [31]:
for i in range(5):
    empty[:,i]=i
empty

array([[0., 1., 2., 3., 4.]])