# Array stacking

In [2]:
import numpy as np

In [6]:
a=np.random.randint(1,10,(2,3))

### Horizontal Stack

In [5]:
a

array([[9, 1],
       [9, 3],
       [8, 7]], dtype=int32)

In [8]:
b=np.arange(1,10).reshape(3,3)

In [9]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
c=2*b

In [13]:
c

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [15]:
np.hstack((b,c))

array([[ 1,  2,  3,  2,  4,  6],
       [ 4,  5,  6,  8, 10, 12],
       [ 7,  8,  9, 14, 16, 18]])

In [17]:
np.column_stack((b,c))

array([[ 1,  2,  3,  2,  4,  6],
       [ 4,  5,  6,  8, 10, 12],
       [ 7,  8,  9, 14, 16, 18]])

In [19]:
np.concatenate((b,c),axis=1)

array([[ 1,  2,  3,  2,  4,  6],
       [ 4,  5,  6,  8, 10, 12],
       [ 7,  8,  9, 14, 16, 18]])

### Vertical Stack

In [20]:
np.vstack((b,c))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [25]:
np.row_stack((b,c))

C:\Users\habib\AppData\Local\Temp\ipykernel_22092\2322955851.py:1: DeprecationWarning: `row_stack` alias is deprecated. Use `np.vstack` directly.
  np.row_stack((b,c))


array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [24]:
np.concatenate((b,c),axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

### Depth Stack

In [26]:
np.dstack((b,c))

array([[[ 1,  2],
        [ 2,  4],
        [ 3,  6]],

       [[ 4,  8],
        [ 5, 10],
        [ 6, 12]],

       [[ 7, 14],
        [ 8, 16],
        [ 9, 18]]])