# Array Indexing and Slicing

In [1]:
import numpy as np

In [2]:
arr=np.array([1,2,3,4,5])


In [3]:
print(arr)

[1 2 3 4 5]


In [5]:
arr[0]

np.int64(1)

In [6]:
arr[-1]

np.int64(5)

In [7]:
print(arr[-1])

5


In [8]:
arr1=np.random.randint(1,10,size=(3,3))

In [10]:
print(arr1)

[[7 7 3]
 [1 4 1]
 [1 3 5]]


In [11]:
print(arr1[0][1])

7


In [12]:
print(arr1[0,1])

7


In [13]:
arr2=np.random.randint(1,10,size=(2,3,3))

In [14]:
print(arr2)

[[[2 5 9]
  [9 8 1]
  [6 5 1]]

 [[6 6 2]
  [9 5 2]
  [8 1 4]]]


In [16]:
print(arr2[0,2,2])

1


# Slicing

In [17]:
print(arr)

[1 2 3 4 5]


In [18]:
arr[0:3]

array([1, 2, 3])

In [19]:
arr[:3]

array([1, 2, 3])

In [21]:
arr[2: ]

array([3, 4, 5])

In [22]:
arr1

array([[7, 7, 3],
       [1, 4, 1],
       [1, 3, 5]], dtype=int32)

In [25]:
arr1[:2,:2]

array([[7, 7],
       [1, 4]], dtype=int32)