# Manipulating array shapes
    

1.reshape()

2.resize() 

3.flatten() 

4.defining array shape

5.revel()

#### reshape()

In [2]:
import numpy as np

In [3]:
a=np.array([[1,2,3],
            [4,5,6]])

In [4]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
a.shape

(2, 3)

In [6]:
a_reshape= np.reshape(a,(3,2))

In [7]:
a_reshape

array([[1, 2],
       [3, 4],
       [5, 6]])

In [8]:
a_reshape.shape

(3, 2)

#### resize()

In [9]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
a_resized=np.resize(a,(4,3))

In [14]:
a_resized

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

# revel()

In [15]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
b=np.random.randint(1,10,(2,3))

In [18]:
b

array([[1, 6, 7],
       [8, 3, 5]], dtype=int32)

In [19]:
b_ravel=np.ravel(b)

In [20]:
b_ravel

array([1, 6, 7, 8, 3, 5], dtype=int32)

In [21]:
b

array([[1, 6, 7],
       [8, 3, 5]], dtype=int32)

In [22]:
b_flattened=b.flatten()

In [24]:
b_flattened

array([1, 6, 7, 8, 3, 5], dtype=int32)

In [25]:
b_ravel[0]=0

In [26]:
b

array([[0, 6, 7],
       [8, 3, 5]], dtype=int32)

In [33]:
b_flattened # return a copy of the array,always allocates a new memory

array([100,   6,   7,   8,   3,   5], dtype=int32)

In [29]:
b_flattened[0]=100

In [31]:
b_flattened

array([100,   6,   7,   8,   3,   5], dtype=int32)

In [32]:
b

array([[0, 6, 7],
       [8, 3, 5]], dtype=int32)

#### defining array shape

In [34]:
a


array([[1, 2, 3],
       [4, 5, 6]])

In [35]:
a.shape=(3,2)

In [36]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])